// <auto-generated />
using System;
using HSPSpecialist.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HSPSpecialist.Migrations
{
    [DbContext(typeof(SpecialistContext))]
    [Migration("20211017080629_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HSPSpecialist.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Service");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CreatedBy = "S1234567C",
                            CreatedDate = new DateTime(2021, 10, 17, 16, 6, 28, 886, DateTimeKind.Local).AddTicks(6130),
                            Description = "testServices",
                            IsDeleted = false,
                            LastUpdatedBy = "S234567C",
                            LastUpdatedDate = new DateTime(2021, 10, 17, 16, 6, 28, 886, DateTimeKind.Local).AddTicks(6573)
                        });
                });

            modelBuilder.Entity("HSPSpecialist.Models.Specialist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Contact")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NRIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Services")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Specialist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "BLK221 PENDING ROAD #08-149",
                            Available = true,
                            Contact = 7697807,
                            CreatedBy = "S1234567C",
                            CreatedDate = new DateTime(2021, 10, 17, 16, 6, 28, 884, DateTimeKind.Local).AddTicks(7847),
                            Email = "test@singnet.com",
                            IsDeleted = false,
                            LastUpdatedBy = "S234567C",
                            LastUpdatedDate = new DateTime(2021, 10, 17, 16, 6, 28, 885, DateTimeKind.Local).AddTicks(6072),
                            NRIC = "S1234567C",
                            Name = "Milo",
                            Services = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
